### ISSUE TITLE
OSError while executing example

### ISSUE THREAD

**Issue by Mettphysik** [bill-connelly/rpg#6]
Hi,

I am trying to run the RPG example on my RPi3. The following error occurs and google offers no help:

ioctl FBIOPUT_VSCREENINFO: Invalid argument
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/rpg/__init__.py", line 308, in __init__
    self.capsule = rpigratings.init(resolution[0],resolution[1], colormode)
OSError: Call to fbset subroutine failed.

I already tried rebooting. Any ideas?

Kind regards

**Comment by bill-connelly** [comment]
Hi,

We haven't tested on a RPi3 for a while to be honest. But it looks like
something has changed in the in the underlying C interface with the screen
buffer. I'll see if I can find a Pi3 and do some testing. Feel free to
contact me if you don't hear back in a couple of weeks (sorry you've just
caught me at a really busy time).

**Comment by Mettphysik** [comment]
Hi, 

no problem, thanks for letting me know! I might retry on a RPi4, would you expect it to run smoothly there? 

Again, thanks for your support :)

**Comment by bill-connelly** [comment]
Hi,

So first off, can you tell me the output of this command:

    cat /etc/os-release

Second, we got around to some testing. Things are complex. We suspect your issue comes from using a very old version of Raspbian [though the output of the above will tell us that]. I want to tell you to upgrade to a recent version. However, the most recent versions of Raspbian also break RPG because they have completely gotten rid of wiringPi, which is how we listened and output digital pulses. So we need to fix that.

So fundamentally, watch this space. I'll let you know when up update the software.
